version: '2'

services:

### Applications Code Container #############################

    applications:
      image: tianon/true

### Workspace Utilities Container ###########################

    workspace:
      build:
        context: ./workspace
        args:
          - INSTALL_MONGO=${WORKSPACE_INSTALL_MONGO}
          - INSTALL_NODE=${WORKSPACE_INSTALL_NODE}
          - NPM_REGISTRY=${WORKSPACE_NPM_REGISTRY}
          - INSTALL_PG_CLIENT=${WORKSPACE_INSTALL_PG_CLIENT}
          - TZ=${WORKSPACE_TIMEZONE}
      volumes_from:
        - applications
      extra_hosts:
        - "dockerhost:${DOCKER_HOST_IP}"
      ports:
        - "22:22"
      tty: true
      volumes:
        - ./code:/var/www

    php-fpm:
      build:
        context: ./php-fpm
        args:
          - INSTALL_PGSQL=${PHP_FPM_INSTALL_PGSQL}
          - INSTALL_PG_CLIENT=${PHP_FPM_INSTALL_PG_CLIENT}
      volumes_from:
        - applications
      volumes:
        - ./php-fpm/php.ini:/usr/local/etc/php/php.ini
        - ./code:/var/www
      expose:
        - "9000"
      depends_on:
        - workspace
      extra_hosts:
        - "dockerhost:${DOCKER_HOST_IP}"
      environment:
        - PHP_IDE_CONFIG=${PHP_IDE_CONFIG}

    nginx:
      build:
        context: ./nginx
        args:
          - PHP_UPSTREAM_CONTAINER=${NGINX_PHP_UPSTREAM_CONTAINER}
          - PHP_UPSTREAM_PORT=${NGINX_PHP_UPSTREAM_PORT}
      volumes_from:
        - applications
      volumes:
        - ./code:/var/www
        - ./site.conf:/etc/nginx/conf.d/default.conf
      ports:
        - "${NGINX_HOST_HTTP_PORT}:80" # Modify
        - "${NGINX_HOST_HTTPS_PORT}:443" # Modify
      depends_on:
        - php-fpm

    mysql:
      build:
        context: ./mysql
        args:
          - MYSQL_VERSION=${MYSQL_VERSION}
      environment:
        - MYSQL_DATABASE=${MYSQL_DATABASE} # Modifi
        - MYSQL_USER=${MYSQL_USER} # Modify 
        - MYSQL_PASSWORD=${MYSQL_PASSWORD} # Modify
        - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD} # Modify
        - TZ=${WORKSPACE_TIMEZONE}
      ports:
        - "3306:3306"

 volumes:
   mysql:
     driver: "local"
